spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://desperadoccy.club:3306/SSAT
    username: SSAT
    password: SSAT2020

server:
  port: 8888
  servlet:
    session:
      cookie:
        http-only: false

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: pers.ccy.**.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

